### ISSUE TITLE
Add ignore regex for cljs files on the classpath

### ISSUE THREAD

**Issue by martintrojer** [thheller/shadow-build#23]
If you use libraries which bundles cljs they are included in shadow-build's cljs and make everything break horribly.

I'd like to add a regex, which is used to filter out cljs from libraries I depend on.

**Comment by thheller** [comment]
Do you have an example which library does this? We had this issue before (#13, magnars/prone#21) but unfortunately some libraries seem to ship javascript they should not ship.

Do the problematic libraries include ```.cljs``` files or only the compiled ```.js```?

**Comment by martintrojer** [comment]
Its indeed prone

**Comment by thheller** [comment]
Just pushed a fix, will test and push a release later. If you want to give it a shot clone master and try it like

```clojure
(-> (cljs/init-state)
    (update-in [:ignore-patterns] conj #"^prone/generated/")
    ...)
```

(must be used before ```find-resources-...```).

**Comment by thheller** [comment]
Just release alpha13.

See the example above. You'll also need to delete the jar manifest directory (defaults to ```"target/shadow-build/jar-manifest"```) since jars are usually only processed once to speed things up a bit.

**Comment by martintrojer** [comment]
:+1:
