### ISSUE TITLE
Don't automatically attempt rebuild on error 

### ISSUE THREAD

**Issue by dvcrn** [thheller/shadow-build#25]
When running `watch-and-repeat` or `devtools/start-loop` and there is a error (be it syntax or namespacing) in one of the source fields, shadow-build will print out the stacktrace and attempts re-building, but that multiple times a second without changes to the source files. 

shadow-build should wait until files have changed before attempting to re-build. If nothing changed it will just run into the same error again and again.

**Comment by thheller** [comment]
fix in `[thheller/shadow-build "1.0.153"]`
