### ISSUE TITLE
build tests without executing them

### ISSUE THREAD

**Issue by shaunlebron** [thheller/shadow-build#26]
It looks like I have to run `execute-all-tests` to build AND run the tests. Could we have a version which only builds them?  That way, we can defer their execution to a separate step in CI to preserve its status code (as you mentioned [here](https://github.com/shaunlebron/parinfer/pull/55#issuecomment-159055116))

**Comment by thheller** [comment]
I separated the creation of the test runner from the execution and it is now simpler to just create the runner. Updated the `build.clj` [1] with an example to just create a runner and autotest.

[1] https://github.com/shaunlebron/parinfer/pull/57
