### ISSUE TITLE
What are your thoughts on a simple interface so a user can add their own custom compiler pass?

### ISSUE THREAD

**Issue by jobez** [thheller/shadow-build#28]
Up for a PR for one?

**Comment by thheller** [comment]
Hey, what do you have in mind? Which compiler in particular? CLJS or Closure?

Generally I'm open to anything useful.

**Comment by jobez** [comment]
Closure. Ok cool!

**Comment by thheller** [comment]
I just pushed an update that should make this pretty relatively simple.

https://github.com/thheller/shadow-build/commit/a94b5a3f4a732bec429dc150e46d3a5de73d647b

You can now call `(shadow.cljs.build/add-closure-configurator compiler-state callback-fn)` where `callback-fn` has the signature `(fn [compiler compiler-options])`. An example of how to add a pass is available at [1]. It is added by default in `init-state` at [2].

I'll cut a new release if this works for you. Let me know if this suits your needs.

[1] https://github.com/thheller/shadow-build/blob/a94b5a3f4a732bec429dc150e46d3a5de73d647b/src/clj/shadow/cljs/build.clj#L1634-L1635
[2] https://github.com/thheller/shadow-build/blob/a94b5a3f4a732bec429dc150e46d3a5de73d647b/src/clj/shadow/cljs/build.clj#L2221

**Comment by jobez** [comment]
Awesome! Thanks so much!

**Comment by thheller** [comment]
I just pushed `[thheller/shadow-build "1.0.197"]` which includes this change.

**Comment by jobez** [comment]
i am very appreciative!
